### ISSUE TITLE
USER STORY: Create Booking

### ISSUE THREAD

**Issue by Stojj2** [Stojj2/Portfolio-Project-4#1]
![Image](https://github.com/Stojj2/Portfolio-Project-4/assets/114947572/cece3909-7b83-4feb-81b6-dc3b18a1968f)

As a **customer** I can **view the list of available times offered by the salon** so that **I can book the one that suits my needs.**

## Acceptance Criteria
  - Logged in users can see booking view
  - Non-registered users receive a message that only registered users can see available time slots. A link for registration should be available from this page 
  - List of all available time slots

## Tasks
- [x] Create HTML template
- [x] Create database model for storing booked appointments
- [x] Create the Python view code
