### ISSUE TITLE
USER STORY: Welcome/About Page

### ISSUE THREAD

**Issue by Stojj2** [Stojj2/Portfolio-Project-4#10]
![Image](https://github.com/Stojj2/Portfolio-Project-4/assets/114947572/274050c4-4249-4c3c-a4cd-0fa1149ba732)
![Image](https://github.com/Stojj2/Portfolio-Project-4/assets/114947572/f29cff5a-4872-4b7e-b7ea-08714ee3a665)

As a **user** I can **get basic information about the salon without login in** so that **I am aware of open times and location**

## Acceptance Criteria
  - Home page with picture of the salon and company information
  - About page with information about the hair salon and the staff

## Tasks
- [x] Create a Django standard project
- [x] Create a base.html file to provide navigation bar and footer
- [x] Create a home.html file that looks like the home Wireframe
- [x] Create a about.html file that looks like the about Wireframe
