### ISSUE TITLE
USER STORY: Account Registration

### ISSUE THREAD

**Issue by Stojj2** [Stojj2/Portfolio-Project-4#9]
![Image](https://github.com/Stojj2/Portfolio-Project-4/assets/114947572/fcc8f737-df5e-4274-9a12-41cfa071b138)

As a **customer** I can **create a user account** so that **I can book and view my appointments**

## Acceptance Criteria
  - Register an account with first name, last name, phone, and email information.

## Tasks
- [x] Create a postgres databas for user information
- [x] Create a registration.html file for for registration data
- [x] Create a view for taking data from registration registration.html page and storing it in postgres database
